version: '3'

services:
  jupyterlab:
    build: .
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:8888:8888"
    command: jupyter-lab --port=8888 --ip=0.0.0.0 --allow-root --NotebookApp.token=''